import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google';

import "./globals.css";
import Providers from '@/components/Providers';
// import MainNav from "@/components/layout/MainNav";

const Plex_Sans = IBM_Plex_Sans({
  weight: '200',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen flex flex-col ">
      <body className={`${Plex_Sans.className} flex-grow flex`}>
        <Providers>
          {/* <MainNav /> */}
          <div className="flex flex-col flex-grow">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
