import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google'

import "./globals.css";
import Providers from '@/components/Providers'
import Navbar from "@/components/layout/Navbar";

const Plex_Sans = IBM_Plex_Sans({
  weight: '200',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Plex_Sans.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
